const PRODUCTS_GET_LIST = 'PRODUCTS_GET_LIST';
const SHOP_ADD_PRODUCT = 'SHOP_ADD_PRODUCT';
const SHOP_REMOVE_PRODUCT = 'SHOP_REMOVE_PRODUCT';
const SHOP_REMOVEALL_PRODUCT = 'SHOP_REMOVEALL_PRODUCT';

export default {
	PRODUCTS_GET_LIST,
    SHOP_ADD_PRODUCT,
    SHOP_REMOVE_PRODUCT,
    SHOP_REMOVEALL_PRODUCT
}