const PRODUCTS_GET_LIST = 'PRODUCTS_GET_LIST';
const SHOP_ADD_PRODUCT = 'SHOP_ADD_PRODUCT';
const SHOP_CLEAR = 'SHOP_CLEAR';

export default {
	PRODUCTS_GET_LIST,
    SHOP_ADD_PRODUCT,
    SHOP_CLEAR
}